var annotated =
[
    [ "Catch", null, [
      [ "Detail", null, [
        [ "BorgType", "df/d22/struct_catch_1_1_detail_1_1_borg_type.html", "df/d22/struct_catch_1_1_detail_1_1_borg_type" ],
        [ "TrueType", "df/d31/struct_catch_1_1_detail_1_1_true_type.html", "df/d31/struct_catch_1_1_detail_1_1_true_type" ],
        [ "FalseType", "d5/ddc/struct_catch_1_1_detail_1_1_false_type.html", "d5/ddc/struct_catch_1_1_detail_1_1_false_type" ],
        [ "IsStreamInsertable", "d9/d1f/struct_catch_1_1_detail_1_1_is_stream_insertable.html", "d9/d1f/struct_catch_1_1_detail_1_1_is_stream_insertable" ],
        [ "StringMakerBase", "d9/dda/struct_catch_1_1_detail_1_1_string_maker_base.html", null ],
        [ "StringMakerBase< true >", "df/dc5/struct_catch_1_1_detail_1_1_string_maker_base_3_01true_01_4.html", null ],
        [ "Approx", "da/d1c/class_catch_1_1_detail_1_1_approx.html", "da/d1c/class_catch_1_1_detail_1_1_approx" ]
      ] ],
      [ "Internal", null, [
        [ "OperatorTraits", "d3/dda/struct_catch_1_1_internal_1_1_operator_traits.html", null ],
        [ "OperatorTraits< IsEqualTo >", "d5/d0d/struct_catch_1_1_internal_1_1_operator_traits_3_01_is_equal_to_01_4.html", null ],
        [ "OperatorTraits< IsNotEqualTo >", "d9/d37/struct_catch_1_1_internal_1_1_operator_traits_3_01_is_not_equal_to_01_4.html", null ],
        [ "OperatorTraits< IsLessThan >", "d1/d7d/struct_catch_1_1_internal_1_1_operator_traits_3_01_is_less_than_01_4.html", null ],
        [ "OperatorTraits< IsGreaterThan >", "d4/d58/struct_catch_1_1_internal_1_1_operator_traits_3_01_is_greater_than_01_4.html", null ],
        [ "OperatorTraits< IsLessThanOrEqualTo >", "d7/df4/struct_catch_1_1_internal_1_1_operator_traits_3_01_is_less_than_or_equal_to_01_4.html", null ],
        [ "OperatorTraits< IsGreaterThanOrEqualTo >", "d1/d8d/struct_catch_1_1_internal_1_1_operator_traits_3_01_is_greater_than_or_equal_to_01_4.html", null ],
        [ "Evaluator", "dc/da8/class_catch_1_1_internal_1_1_evaluator.html", null ],
        [ "Evaluator< T1, T2, IsEqualTo >", "d6/d05/struct_catch_1_1_internal_1_1_evaluator_3_01_t1_00_01_t2_00_01_is_equal_to_01_4.html", null ],
        [ "Evaluator< T1, T2, IsNotEqualTo >", "d7/d1d/struct_catch_1_1_internal_1_1_evaluator_3_01_t1_00_01_t2_00_01_is_not_equal_to_01_4.html", null ],
        [ "Evaluator< T1, T2, IsLessThan >", "d7/d54/struct_catch_1_1_internal_1_1_evaluator_3_01_t1_00_01_t2_00_01_is_less_than_01_4.html", null ],
        [ "Evaluator< T1, T2, IsGreaterThan >", "dd/dc4/struct_catch_1_1_internal_1_1_evaluator_3_01_t1_00_01_t2_00_01_is_greater_than_01_4.html", null ],
        [ "Evaluator< T1, T2, IsGreaterThanOrEqualTo >", "df/d31/struct_catch_1_1_internal_1_1_evaluator_3_01_t1_00_01_t2_00_01_is_greater_than_or_equal_to_01_4.html", null ],
        [ "Evaluator< T1, T2, IsLessThanOrEqualTo >", "d3/dac/struct_catch_1_1_internal_1_1_evaluator_3_01_t1_00_01_t2_00_01_is_less_than_or_equal_to_01_4.html", null ]
      ] ],
      [ "Matchers", null, [
        [ "Impl", null, [
          [ "Generic", null, [
            [ "AllOf", "d8/de7/class_catch_1_1_matchers_1_1_impl_1_1_generic_1_1_all_of.html", "d8/de7/class_catch_1_1_matchers_1_1_impl_1_1_generic_1_1_all_of" ],
            [ "AnyOf", "d7/d4f/class_catch_1_1_matchers_1_1_impl_1_1_generic_1_1_any_of.html", "d7/d4f/class_catch_1_1_matchers_1_1_impl_1_1_generic_1_1_any_of" ]
          ] ],
          [ "StdString", null, [
            [ "Equals", "dc/d22/struct_catch_1_1_matchers_1_1_impl_1_1_std_string_1_1_equals.html", "dc/d22/struct_catch_1_1_matchers_1_1_impl_1_1_std_string_1_1_equals" ],
            [ "Contains", "d0/dac/struct_catch_1_1_matchers_1_1_impl_1_1_std_string_1_1_contains.html", "d0/dac/struct_catch_1_1_matchers_1_1_impl_1_1_std_string_1_1_contains" ],
            [ "StartsWith", "d2/d26/struct_catch_1_1_matchers_1_1_impl_1_1_std_string_1_1_starts_with.html", "d2/d26/struct_catch_1_1_matchers_1_1_impl_1_1_std_string_1_1_starts_with" ],
            [ "EndsWith", "d5/d98/struct_catch_1_1_matchers_1_1_impl_1_1_std_string_1_1_ends_with.html", "d5/d98/struct_catch_1_1_matchers_1_1_impl_1_1_std_string_1_1_ends_with" ]
          ] ],
          [ "Matcher", "dc/d2c/struct_catch_1_1_matchers_1_1_impl_1_1_matcher.html", "dc/d2c/struct_catch_1_1_matchers_1_1_impl_1_1_matcher" ],
          [ "MatcherImpl", "d2/dfc/struct_catch_1_1_matchers_1_1_impl_1_1_matcher_impl.html", "d2/dfc/struct_catch_1_1_matchers_1_1_impl_1_1_matcher_impl" ]
        ] ]
      ] ],
      [ "NonCopyable", "d8/d09/class_catch_1_1_non_copyable.html", "d8/d09/class_catch_1_1_non_copyable" ],
      [ "SafeBool", "df/d0f/class_catch_1_1_safe_bool.html", "df/d0f/class_catch_1_1_safe_bool" ],
      [ "pluralise", "df/dc0/struct_catch_1_1pluralise.html", "df/dc0/struct_catch_1_1pluralise" ],
      [ "SourceLineInfo", "df/dc5/struct_catch_1_1_source_line_info.html", "df/dc5/struct_catch_1_1_source_line_info" ],
      [ "StreamEndStop", "de/d32/struct_catch_1_1_stream_end_stop.html", "de/d32/struct_catch_1_1_stream_end_stop" ],
      [ "NotImplementedException", "d3/da1/class_catch_1_1_not_implemented_exception.html", "d3/da1/class_catch_1_1_not_implemented_exception" ],
      [ "IGeneratorInfo", "d1/d78/struct_catch_1_1_i_generator_info.html", "d1/d78/struct_catch_1_1_i_generator_info" ],
      [ "IGeneratorsForTest", "da/d20/struct_catch_1_1_i_generators_for_test.html", "da/d20/struct_catch_1_1_i_generators_for_test" ],
      [ "Ptr", "d8/d31/class_catch_1_1_ptr.html", "d8/d31/class_catch_1_1_ptr" ],
      [ "IShared", "d2/d4f/struct_catch_1_1_i_shared.html", "d2/d4f/struct_catch_1_1_i_shared" ],
      [ "SharedImpl", "d0/dc0/struct_catch_1_1_shared_impl.html", "d0/dc0/struct_catch_1_1_shared_impl" ],
      [ "IContext", "d1/daf/struct_catch_1_1_i_context.html", "d1/daf/struct_catch_1_1_i_context" ],
      [ "IMutableContext", "dc/d78/struct_catch_1_1_i_mutable_context.html", "dc/d78/struct_catch_1_1_i_mutable_context" ],
      [ "ITestCase", "d8/d1b/struct_catch_1_1_i_test_case.html", "d8/d1b/struct_catch_1_1_i_test_case" ],
      [ "ITestCaseRegistry", "d3/dd5/struct_catch_1_1_i_test_case_registry.html", "d3/dd5/struct_catch_1_1_i_test_case_registry" ],
      [ "MethodTestCase", "dc/de4/class_catch_1_1_method_test_case.html", "dc/de4/class_catch_1_1_method_test_case" ],
      [ "NameAndDesc", "d0/d7f/struct_catch_1_1_name_and_desc.html", "d0/d7f/struct_catch_1_1_name_and_desc" ],
      [ "AutoReg", "d4/d92/struct_catch_1_1_auto_reg.html", "d4/d92/struct_catch_1_1_auto_reg" ],
      [ "ResultWas", "d1/d43/struct_catch_1_1_result_was.html", "d1/d43/struct_catch_1_1_result_was" ],
      [ "ResultDisposition", "d8/dfd/struct_catch_1_1_result_disposition.html", "d8/dfd/struct_catch_1_1_result_disposition" ],
      [ "AssertionInfo", "d4/d90/struct_catch_1_1_assertion_info.html", "d4/d90/struct_catch_1_1_assertion_info" ],
      [ "AssertionResultData", "df/d51/struct_catch_1_1_assertion_result_data.html", "df/d51/struct_catch_1_1_assertion_result_data" ],
      [ "AssertionResult", "d9/dc8/class_catch_1_1_assertion_result.html", "d9/dc8/class_catch_1_1_assertion_result" ],
      [ "TestFailureException", "d3/ddd/struct_catch_1_1_test_failure_exception.html", null ],
      [ "ExpressionLhs", "d6/d8d/class_catch_1_1_expression_lhs.html", "d6/d8d/class_catch_1_1_expression_lhs" ],
      [ "CopyableStream", "da/ddf/struct_catch_1_1_copyable_stream.html", "da/ddf/struct_catch_1_1_copyable_stream" ],
      [ "ResultBuilder", "d0/d28/class_catch_1_1_result_builder.html", "d0/d28/class_catch_1_1_result_builder" ],
      [ "StringMaker", "db/daf/struct_catch_1_1_string_maker.html", null ],
      [ "StringMaker< T * >", "de/dc1/struct_catch_1_1_string_maker_3_01_t_01_5_01_4.html", null ],
      [ "StringMaker< R C::* >", "d2/da4/struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html", null ],
      [ "MessageInfo", "db/d87/struct_catch_1_1_message_info.html", "db/d87/struct_catch_1_1_message_info" ],
      [ "MessageBuilder", "da/ddb/struct_catch_1_1_message_builder.html", "da/ddb/struct_catch_1_1_message_builder" ],
      [ "ScopedMessage", "d4/d3e/class_catch_1_1_scoped_message.html", "d4/d3e/class_catch_1_1_scoped_message" ],
      [ "IResultCapture", "db/d82/struct_catch_1_1_i_result_capture.html", "db/d82/struct_catch_1_1_i_result_capture" ],
      [ "IRunner", "db/dd9/struct_catch_1_1_i_runner.html", "db/dd9/struct_catch_1_1_i_runner" ],
      [ "SectionInfo", "db/d6f/struct_catch_1_1_section_info.html", "db/d6f/struct_catch_1_1_section_info" ],
      [ "Counts", "de/d8f/struct_catch_1_1_counts.html", "de/d8f/struct_catch_1_1_counts" ],
      [ "Totals", "d4/da0/struct_catch_1_1_totals.html", "d4/da0/struct_catch_1_1_totals" ],
      [ "Timer", "d6/d37/class_catch_1_1_timer.html", "d6/d37/class_catch_1_1_timer" ],
      [ "Section", "db/dc8/class_catch_1_1_section.html", "db/dc8/class_catch_1_1_section" ],
      [ "IGenerator", "d4/d15/struct_catch_1_1_i_generator.html", "d4/d15/struct_catch_1_1_i_generator" ],
      [ "BetweenGenerator", "da/d41/class_catch_1_1_between_generator.html", "da/d41/class_catch_1_1_between_generator" ],
      [ "ValuesGenerator", "d4/db6/class_catch_1_1_values_generator.html", "d4/db6/class_catch_1_1_values_generator" ],
      [ "CompositeGenerator", "df/d2d/class_catch_1_1_composite_generator.html", "df/d2d/class_catch_1_1_composite_generator" ],
      [ "IRegistryHub", "d6/d0d/struct_catch_1_1_i_registry_hub.html", "d6/d0d/struct_catch_1_1_i_registry_hub" ],
      [ "IMutableRegistryHub", "d8/d9e/struct_catch_1_1_i_mutable_registry_hub.html", "d8/d9e/struct_catch_1_1_i_mutable_registry_hub" ],
      [ "IExceptionTranslator", "db/d6d/struct_catch_1_1_i_exception_translator.html", "db/d6d/struct_catch_1_1_i_exception_translator" ],
      [ "IExceptionTranslatorRegistry", "d4/dd5/struct_catch_1_1_i_exception_translator_registry.html", "d4/dd5/struct_catch_1_1_i_exception_translator_registry" ],
      [ "ExceptionTranslatorRegistrar", "d0/dd3/class_catch_1_1_exception_translator_registrar.html", "d0/dd3/class_catch_1_1_exception_translator_registrar" ],
      [ "TagAlias", "de/db5/struct_catch_1_1_tag_alias.html", "de/db5/struct_catch_1_1_tag_alias" ],
      [ "RegistrarForTagAliases", "d7/d9b/struct_catch_1_1_registrar_for_tag_aliases.html", "d7/d9b/struct_catch_1_1_registrar_for_tag_aliases" ],
      [ "Option", "df/da2/class_catch_1_1_option.html", "df/da2/class_catch_1_1_option" ],
      [ "ITagAliasRegistry", "d3/dc4/struct_catch_1_1_i_tag_alias_registry.html", "d3/dc4/struct_catch_1_1_i_tag_alias_registry" ],
      [ "TestCaseInfo", "d1/d61/struct_catch_1_1_test_case_info.html", "d1/d61/struct_catch_1_1_test_case_info" ],
      [ "TestCase", "d5/d5a/class_catch_1_1_test_case.html", "d5/d5a/class_catch_1_1_test_case" ]
    ] ],
    [ "SteamVdfParse", "db/d3c/namespace_steam_vdf_parse.html", "db/d3c/namespace_steam_vdf_parse" ],
    [ "Ui", "dc/df0/namespace_ui.html", null ],
    [ "BorderlessWindow", "d2/d4b/class_borderless_window.html", "d2/d4b/class_borderless_window" ],
    [ "Browser", "db/dc8/class_browser.html", "db/dc8/class_browser" ],
    [ "Database", "dc/d83/class_database.html", "dc/d83/class_database" ],
    [ "Game", "dd/db8/struct_game.html", "dd/db8/struct_game" ],
    [ "Library", "d7/d55/class_library.html", "d7/d55/class_library" ],
    [ "MainPanel", "d1/d88/class_main_panel.html", "d1/d88/class_main_panel" ],
    [ "TabLabel", "d2/dda/class_tab_label.html", "d2/dda/class_tab_label" ],
    [ "UnixPanel", "de/d68/class_unix_panel.html", "de/d68/class_unix_panel" ],
    [ "UnixWindow", "d2/d2b/class_unix_window.html", "d2/d2b/class_unix_window" ],
    [ "WinPanel", "d6/d55/class_win_panel.html", "d6/d55/class_win_panel" ],
    [ "WinWindow", "d8/db8/class_win_window.html", "d8/db8/class_win_window" ]
];